baseURL = "https://agecal.net"
title   = "Free Age Analysis Tool"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "agecal.net" # This message is only used by the RSS template.

googleAnalytics = "G-JY6K1P3V0K"
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "agecal.net team"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Metadata mostly used in document's head
  # 
  description = "📆 Calculate age from date of birth"
  keywords = "Age calcualtion, free age calculator, how old I am, my age, date of birth, dog age, cat age, life facts, age facts"

  # Home subtitle of the index page.
  #
  homeSubtitle = "Calculate age using date of birth"

  # Set a background for the homepage
  #backgroundImage = "/images/background.jpg"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  #
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  #
  disableReadOtherPosts = false

  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Sharing buttons
  #
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  #
  enableSharingButtons = true

  # Global language menu
  #
  # Enables the global language menu.
  #
  enableGlobalLanguageMenu = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  #
  customCSS = ["/css/agecal.net.css"]
  customJS  = ["/js/calculate_age.js"]

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  #
  justifyContent = false  # Set "text-align: justify" to .post-content.

  # Integrate Plausible.io
  # plausibleDataDomain = 'test.com'
  # plausibleScriptSource = 'https://plausible.io/js/script.js'

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
    trademark = true
    rss = false
    copyright = true
    author = false

    topText = []
    bottomText = [
      "Made with &#10084; by <a href=\"https://x.com/AndriiShylenko\">Artomatica</a>"
    ]

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = "📆"
    logoText     = "Agecal.net"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = true
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorAnimate  = "4s"
    # Append the current url pathname to logoText 
    # logoCursorPathname = true

  # Commento is more than just a comments widget you can embed — 
  # it’s a return to the roots of the internet. 
  # An internet without the tracking and invasions of privacy. 
  # An internet that is simple and lightweight. 
  # An internet that is focused on interesting discussions, not ads. 
  # A better internet.
  # Uncomment this to enable Commento.
  #
  # [params.commento]
  #   url = ""

  # Uncomment this if you want a portrait on your start page
  #
  # [params.portrait]
  #   path     = "/img/image.jpg"
  #   alt      = "Portrait"
  #   maxWidth = "50px"

  # Social icons
  #[[params.social]]
  #  name = "twitter"
  #  url  = ""

  #[[params.social]]
  #  name = "email"
  #  url  = ""

  #[[params.social]]
  #  name = "github"
  #  url  = ""

  #[[params.social]]
  #  name = "linkedin"
  #  url  = ""

  #[[params.social]]
  #  name = "stackoverflow"
  #  url  = ""

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1
  
[module]
[[module.imports]]
    path = 'github.com/hugomods/images'
    disable = false
    
[[module.imports]]
    path = 'github.com/hugomods/bootstrap'
    disable = false

[languages]
  [languages.en]
    subtitle  = "Age calculator"
    weight    = 1
    copyright = ''

[menu]
  [[menu.main]]
    identifier = "AgeCalculator"
    name       = "Age Calculator"
    url        = "/"
    weight     = 1
  [[menu.main]]
    identifier = "LifeInWeeks"
    name       = "Life In Weeks"
    url        = "pages/life-in-weeks/"
    weight     = 2
  [[menu.main]]
    identifier = "Blog"
    name       = "Blog"
    url        = "posts/"
    weight     = 3
  [[menu.main]]
    identifier = "Contact"
    name       = "Contact"
    url        = "contact/"
    weight     = 4
  [[menu.main]]
    identifier = "Terms"
    name       = "Privacy"
    url        = "/pages/privacy/"
    weight     = 5
